# Generated by Django 4.1.5 on 2023-01-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("age", models.BigIntegerField(blank=True)),
                ("bio", models.TextField(max_length=100)),
                ("register_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["username"],},
        ),
    ]
